spring:
  profiles:
    active: prod
  application:
    name: server
  mustache:
    suffix: .hbs
  data:
    mongodb:
      port: 0
management:
  context-path: /mgmt
logging:
  level:
    org.springframework.security: DEBUG
